package com.mycompany.a3.Servicos.TelasContrato;

import com.mycompany.a3.UsuariosSistemas.TelaCadastroCliente.Cliente;
import com.mycompany.a3.UsuariosSistemas.TelaCadastroPrestador.Prestador;
import com.mycompany.a3.UsuariosSistemas.TelaLogin.TelaLogin;
import com.mycompany.a3.UsuariosSistemas.UsuarioSistema;
import com.mycompany.a3.config.configConexao;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Giovana Ferreira
 */
public final class TelaRecebeContratoPrestador extends javax.swing.JFrame {
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaRecebeContratoPrestador.class.getName());
    private UsuarioSistema usuarioSistema;
    public PreContrato pcSelected = new PreContrato();
    ArrayList<PreContrato> pcList = new ArrayList<>();
    
    /**
     * Creates new form TelaRecebeContratoPrestador
     */
    
    public TelaRecebeContratoPrestador() {
        initComponents();
    }
    
    public TelaRecebeContratoPrestador(UsuarioSistema u) {
        this.usuarioSistema = u;
        initComponents();
        configTela();
        eventos();
        carregarLista();
        carregaAbaPerfil();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtAbas = new javax.swing.JTabbedPane();
        jpnProposta = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPropostas = new javax.swing.JTable();
        btnCancelarPropos = new javax.swing.JButton();
        jpnPerfil = new javax.swing.JPanel();
        lblFoto = new javax.swing.JLabel();
        txtBio = new javax.swing.JTextField();
        lblNome = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        lblCPF = new javax.swing.JLabel();
        lblTelefone = new javax.swing.JLabel();
        lblCep = new javax.swing.JLabel();
        lblEstado = new javax.swing.JLabel();
        lblCidade = new javax.swing.JLabel();
        lblRua = new javax.swing.JLabel();
        lblNumero = new javax.swing.JLabel();
        lblComplemento = new javax.swing.JLabel();
        lblServico = new javax.swing.JLabel();
        lblDataNascimento = new javax.swing.JLabel();
        lblAvaliacao = new javax.swing.JLabel();
        lblSexo = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtCPF = new javax.swing.JTextField();
        txtTelefone = new javax.swing.JTextField();
        txtCep = new javax.swing.JTextField();
        txtEstado = new javax.swing.JTextField();
        txtCidade = new javax.swing.JTextField();
        txtRua = new javax.swing.JTextField();
        txtNumero = new javax.swing.JTextField();
        txtComplemento = new javax.swing.JTextField();
        txtDataNascimento = new javax.swing.JTextField();
        txtAvaliacao1 = new javax.swing.JTextField();
        cmbSexo = new javax.swing.JComboBox<>();
        btnCancelar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        lblCategoria = new javax.swing.JLabel();
        cmbServico = new javax.swing.JComboBox<>();
        cmbCategoria = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblPropostas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblPropostas);

        btnCancelarPropos.setText("Fechar");

        javax.swing.GroupLayout jpnPropostaLayout = new javax.swing.GroupLayout(jpnProposta);
        jpnProposta.setLayout(jpnPropostaLayout);
        jpnPropostaLayout.setHorizontalGroup(
            jpnPropostaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnPropostaLayout.createSequentialGroup()
                .addGroup(jpnPropostaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 883, Short.MAX_VALUE)
                    .addGroup(jpnPropostaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnCancelarPropos)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jpnPropostaLayout.setVerticalGroup(
            jpnPropostaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnPropostaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 437, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnCancelarPropos)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        jtAbas.addTab("Proposta", jpnProposta);

        lblFoto.setText("Foto");
        lblFoto.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblNome.setText("Nome");

        lblEmail.setText("Email");

        lblCPF.setText("CPF");

        lblTelefone.setText("Telefone");

        lblCep.setText("CEP");

        lblEstado.setText("Estado");

        lblCidade.setText("Cidade");

        lblRua.setText("Rua");

        lblNumero.setText("Número");

        lblComplemento.setText("Complemento");

        lblServico.setText("Servico");

        lblDataNascimento.setText("Nascimento");

        lblAvaliacao.setText("Avaliação");

        lblSexo.setText("Sexo");

        cmbSexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnCancelar.setText("Fechar");

        btnExcluir.setText("Excluir");
        btnExcluir.setToolTipText("");

        btnSalvar.setText("Salvar");

        lblCategoria.setText("Categoria");

        cmbServico.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cmbCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jpnPerfilLayout = new javax.swing.GroupLayout(jpnPerfil);
        jpnPerfil.setLayout(jpnPerfilLayout);
        jpnPerfilLayout.setHorizontalGroup(
            jpnPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnPerfilLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpnPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtBio, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jpnPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpnPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jpnPerfilLayout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jpnPerfilLayout.createSequentialGroup()
                            .addGap(103, 103, 103)
                            .addGroup(jpnPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(txtNome, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtEmail, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtCPF, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtTelefone, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtCep, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtDataNascimento, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jpnPerfilLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jpnPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jpnPerfilLayout.createSequentialGroup()
                                .addComponent(lblDataNascimento)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblSexo, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cmbSexo, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(111, 111, 111))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jpnPerfilLayout.createSequentialGroup()
                                .addGroup(jpnPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblRua, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblTelefone)
                                    .addComponent(lblCep)
                                    .addComponent(lblEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(42, 42, 42)
                                .addComponent(txtEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblCPF, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblEmail, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNome, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jpnPerfilLayout.createSequentialGroup()
                                .addComponent(btnCancelar)
                                .addGap(173, 173, 173)
                                .addComponent(btnExcluir)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnSalvar))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jpnPerfilLayout.createSequentialGroup()
                                .addGroup(jpnPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblComplemento)
                                    .addComponent(lblServico, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jpnPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(lblAvaliacao, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblCategoria, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jpnPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jpnPerfilLayout.createSequentialGroup()
                                        .addComponent(txtRua, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(lblNumero)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(txtComplemento, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnPerfilLayout.createSequentialGroup()
                                        .addGroup(jpnPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(cmbCategoria, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(cmbServico, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(224, 224, 224))
                                    .addComponent(txtAvaliacao1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        jpnPerfilLayout.setVerticalGroup(
            jpnPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnPerfilLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpnPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jpnPerfilLayout.createSequentialGroup()
                        .addGroup(jpnPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNome)
                            .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jpnPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblSexo)
                            .addComponent(cmbSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDataNascimento)
                            .addComponent(txtDataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jpnPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblEmail))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jpnPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCPF))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jpnPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTelefone)
                            .addComponent(txtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpnPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCep)
                    .addComponent(txtCep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpnPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtBio)
                    .addGroup(jpnPerfilLayout.createSequentialGroup()
                        .addGroup(jpnPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCidade)
                            .addComponent(txtCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblEstado))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jpnPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblRua)
                            .addComponent(txtRua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNumero)
                            .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jpnPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblComplemento)
                            .addComponent(txtComplemento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jpnPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblServico)
                            .addComponent(cmbServico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jpnPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCategoria)
                            .addComponent(cmbCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)
                        .addGroup(jpnPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblAvaliacao)
                            .addComponent(txtAvaliacao1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 126, Short.MAX_VALUE)
                        .addGroup(jpnPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnCancelar)
                            .addComponent(btnExcluir)
                            .addComponent(btnSalvar))))
                .addContainerGap())
        );

        jtAbas.addTab("Perfil", jpnPerfil);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jtAbas)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jtAbas)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TelaRecebeContratoPrestador().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnCancelarPropos;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JComboBox<String> cmbCategoria;
    private javax.swing.JComboBox<String> cmbServico;
    private javax.swing.JComboBox<String> cmbSexo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel jpnPerfil;
    private javax.swing.JPanel jpnProposta;
    private javax.swing.JTabbedPane jtAbas;
    private javax.swing.JLabel lblAvaliacao;
    private javax.swing.JLabel lblCPF;
    private javax.swing.JLabel lblCategoria;
    private javax.swing.JLabel lblCep;
    private javax.swing.JLabel lblCidade;
    private javax.swing.JLabel lblComplemento;
    private javax.swing.JLabel lblDataNascimento;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblEstado;
    private javax.swing.JLabel lblFoto;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblNumero;
    private javax.swing.JLabel lblRua;
    private javax.swing.JLabel lblServico;
    private javax.swing.JLabel lblSexo;
    private javax.swing.JLabel lblTelefone;
    private javax.swing.JTable tblPropostas;
    private javax.swing.JTextField txtAvaliacao1;
    private javax.swing.JTextField txtBio;
    private javax.swing.JTextField txtCPF;
    private javax.swing.JTextField txtCep;
    private javax.swing.JTextField txtCidade;
    private javax.swing.JTextField txtComplemento;
    private javax.swing.JTextField txtDataNascimento;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtEstado;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtNumero;
    private javax.swing.JTextField txtRua;
    private javax.swing.JTextField txtTelefone;
    // End of variables declaration//GEN-END:variables

    public void configTela(){
        setLocationRelativeTo(null); // centraliza tela
    }

    public void eventos(){
        clickTblPropostas();
        clickBtnFechar();
    }
    
    public String mainQuery(){
         String sql = "SELECT PC.ID, PC.ID_CLIENTE, PC.ID_PRESTADOR," +
                    " PC.VALOR_PROPOSTO, PC.SERVICO, PC.DATA_INICIO_CONTRATO," +
                    " PC.DATA_FIM_CONTRATO, PC.STATUS," +
                    " U.NOME AS NOMECLI, U.EMAIL AS EMAILCLI, U.CPF AS CPFCLI," +
                    " U.TELEFONE AS TELEFONECLI, U.CEP AS CEPCLI," +
                    " U.NUMERO AS NUMEROCLI, U.DATA_NASCIMENTO AS DATANASCCLI," +
                    " U.SEXO AS SEXOCLI, U.CIDADE AS CIDADECLI," +
                    " U.ESTADO AS ESTADOCLI," + 
                    " P.NOME AS NOMEPRES, P.EMAIL AS EMAILPRES, P.CPF AS CPFPRES," +
                    " P.TELEFONE AS TELEFONEPRES, P.CEP AS CEPPRES," +
                    " P.NUMERO AS NUMEROPRES, P.DATA_NASCIMENTO AS DATANASCPRES," +
                    " P.SEXO AS SEXOPRES, P.CIDADE AS CIDADEPRES, P.ESTADO AS ESTADOPRES" +
                    " FROM CONTRATOS PC" + 
                    " LEFT JOIN CLIENTES U" + 
                    " ON (U.ID = PC.ID_CLIENTE)" + 
                    " LEFT JOIN PRESTADORES P" + 
                    " ON (P.ID = PC.ID_PRESTADOR)" + 
                    " WHERE ID_PRESTADOR = ?";
         return sql;
    }

    public void carregarLista(){
        String[] colunas = {"Nome", "Cidade", "Estado", "Data Ini.", "Data Fim",
                            "Valor", "Status"};

        DefaultTableModel model = new DefaultTableModel(colunas, 0);
        tblPropostas.setModel(model);

        String sql = mainQuery();
        
        try (Connection con = configConexao.getConexao();
             PreparedStatement ps = con.prepareStatement(sql)) {
            
            ps.setInt(1, usuarioSistema.getId());

            try(ResultSet rs = ps.executeQuery()){
                while (rs.next()) {
                    PreContrato pc = new PreContrato();
                    pc.setId(rs.getInt("ID"));
                    pc.setIdCliente(rs.getInt("ID_CLIENTE"));
                    pc.setIdPrestador(rs.getInt("ID_PRESTADOR"));
                    pc.setValor(rs.getDouble("VALOR_PROPOSTO"));
                    pc.setDataIni(rs.getDate("DATA_INICIO_CONTRATO"));
                    pc.setDataIni(rs.getDate("DATA_FIM_CONTRATO"));
                    pc.setStatus(rs.getInt("STATUS"));
                    
                    Cliente c = new Cliente();
                    c.setId(rs.getInt("ID_CLIENTE"));
                    c.setNome(rs.getString("NOMECLI"));
                    c.setEmail(rs.getString("EMAILCLI"));
                    c.setCpf(rs.getString("CPFCLI"));
                    c.setTelefone(rs.getString("TELEFONECLI"));
                    c.setCidade(rs.getString("CIDADECLI"));
                    c.setEstado(rs.getString("ESTADOCLI"));
                    c.setCep(rs.getString("CEPCLI"));
                    c.setDataNascimento(rs.getDate("DATANASCCLI"));
                    c.setSexo(rs.getInt("SEXOCLI"));

                    Object[] linha = {
                                        c.getNome(),
                                        c.getCidade(),
                                        c.getEstado(),
                                        rs.getDouble("VALOR_PROPOSTO"),
                                        rs.getDate("DATA_INICIO_CONTRATO"),
                                        rs.getDate("DATA_FIM_CONTRATO"),
                                        rs.getInt("STATUS")
                    };
                    model.addRow(linha);
                    pcList.add(pc);
                }
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, 
                "Erro ao carregar prestadores: " + e.getMessage(),
                "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    public void clickBtnFechar(){
        btnCancelar.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                dispose();
                new TelaLogin().setVisible(true);
            }
        });

        btnCancelarPropos.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                dispose();
                new TelaLogin().setVisible(true);
            }
        });
    }
    
    public void carregaAbaPerfil(){
        String sql = mainQuery();
        
        try (Connection con = configConexao.getConexao();
             PreparedStatement ps = con.prepareStatement(sql)) {
            
            ps.setInt(1, usuarioSistema.getId());

            try(ResultSet rs = ps.executeQuery()){
                while (rs.next()) {
                    Prestador p = new Prestador();
                    p.setId(rs.getInt("ID_PRESTADOR"));
                    p.setNome(rs.getString("NOMEPRES"));
                    p.setEmail(rs.getString("EMAILPRES"));
                    p.setCpf(rs.getString("CPFPRES"));
                    p.setTelefone(rs.getString("TELEFONEPRES"));
                    p.setCidade(rs.getString("CIDADEPRES"));
                    p.setEstado(rs.getString("ESTADOPRES"));
                    p.setCep(rs.getString("CEPPRES"));
                    p.setNumero(rs.getString("NUMEROPRES"));
                    p.setDataNascimento(rs.getDate("DATANASCPRES"));
                    p.setSexo(rs.getInt("SEXOPRES"));
                    
                    txtNome.setText(p.getNome());
                    txtEmail.setText(p.getEmail());
                    txtCPF.setText(p.getCpf());
                    txtTelefone.setText(p.getTelefone());
                    txtCidade.setText(p.getCidade());
                    txtEstado.setText(p.getEstado());
                    txtCep.setText(p.getCep());
                    txtNumero.setText(p.getNumero());
                    txtDataNascimento.setText(p.getDataNascimento().toString());
                    cmbSexo.addItem(String.valueOf(p.getSexo()));
                    cmbSexo.getItemAt(cmbSexo.getSelectedIndex());
                } 
            }
        }catch (SQLException e) {
        JOptionPane.showMessageDialog(null, 
            "Erro ao carregar prestadores: " + e.getMessage(),
            "Erro", JOptionPane.ERROR_MESSAGE);
        } 
    }
    
    public void clickTblPropostas(){
        tblPropostas.addMouseListener(new MouseAdapter(){
            public void mouseClicked(MouseEvent e) {
            int linha = tblPropostas.rowAtPoint(e.getPoint());
           
                if (linha != -1) {
                  pcSelected = pcList.get(linha);
                  new TelaDecisaoContrato(TelaRecebeContratoPrestador.this, true).setVisible(true);
                }           
            }
        });
    }
}
