package com.mycompany.a3.Servicos.TelaPesquisaServicos;

import com.mycompany.a3.Recursos.DataFormatFilter;
import com.mycompany.a3.Servicos.TelasContrato.PreContrato;
import com.mycompany.a3.UsuariosSistemas.TelaCadastroPrestador.Prestador;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.text.AbstractDocument;

/**
 *
 * @author Giovana Ferreira
 */
public class TelaCriaContrato extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaCriaContrato.class.getName());
    TelaEnviaContratoCliente screenMain;

    /**
     * Creates new form TelaCriaContrato
     */
    public TelaCriaContrato(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        configTela();
        eventos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        abaPerfilPrestador = new javax.swing.JPanel();
        lblFotoPerfil = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtBio = new javax.swing.JTextArea();
        txtNome = new javax.swing.JTextField();
        txtDataNascimento = new javax.swing.JTextField();
        lblNome = new javax.swing.JLabel();
        lblDataNascimento = new javax.swing.JLabel();
        lblSexo = new javax.swing.JLabel();
        cmbSexo = new javax.swing.JComboBox<>();
        lblEstado = new javax.swing.JLabel();
        txtEstado = new javax.swing.JTextField();
        lblCidade = new javax.swing.JLabel();
        txtCidade = new javax.swing.JTextField();
        lblTelefone = new javax.swing.JLabel();
        txtTelefone = new javax.swing.JTextField();
        lblDataIni1 = new javax.swing.JLabel();
        lblDataFim1 = new javax.swing.JLabel();
        txtDataIni1 = new javax.swing.JTextField();
        txtDataFim1 = new javax.swing.JTextField();
        lblValor = new javax.swing.JLabel();
        txtValor = new javax.swing.JTextField();
        btnContratar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblFotoPerfil.setText("Foto Perfil");
        lblFotoPerfil.setToolTipText("");
        lblFotoPerfil.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        txtBio.setColumns(20);
        txtBio.setRows(5);
        jScrollPane1.setViewportView(txtBio);

        lblNome.setText("Nome");

        lblDataNascimento.setText("Nascimento");

        lblSexo.setText("Sexo");

        cmbSexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lblEstado.setText("Estado");

        lblCidade.setText("Cidade");

        lblTelefone.setText("Telefone");

        lblDataIni1.setText("Data Inicio");

        lblDataFim1.setText("Data Fim");

        lblValor.setText("Valor");

        btnContratar.setText("Contratar");

        btnCancelar.setText("Fechar");

        javax.swing.GroupLayout abaPerfilPrestadorLayout = new javax.swing.GroupLayout(abaPerfilPrestador);
        abaPerfilPrestador.setLayout(abaPerfilPrestadorLayout);
        abaPerfilPrestadorLayout.setHorizontalGroup(
            abaPerfilPrestadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(abaPerfilPrestadorLayout.createSequentialGroup()
                .addComponent(lblFotoPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(abaPerfilPrestadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(abaPerfilPrestadorLayout.createSequentialGroup()
                        .addGap(385, 385, 385)
                        .addComponent(btnCancelar)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(abaPerfilPrestadorLayout.createSequentialGroup()
                        .addGap(275, 275, 275)
                        .addGroup(abaPerfilPrestadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(abaPerfilPrestadorLayout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addGroup(abaPerfilPrestadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblDataIni1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblValor, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(abaPerfilPrestadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtDataIni1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(abaPerfilPrestadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(abaPerfilPrestadorLayout.createSequentialGroup()
                                        .addComponent(lblDataFim1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtDataFim1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(abaPerfilPrestadorLayout.createSequentialGroup()
                                        .addGap(220, 220, 220)
                                        .addComponent(btnContratar)))
                                .addGap(53, 53, 53))
                            .addGroup(abaPerfilPrestadorLayout.createSequentialGroup()
                                .addGroup(abaPerfilPrestadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblDataNascimento, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblNome, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblEstado, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblTelefone, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(abaPerfilPrestadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(abaPerfilPrestadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(abaPerfilPrestadorLayout.createSequentialGroup()
                                            .addComponent(txtEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(lblCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(txtCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(abaPerfilPrestadorLayout.createSequentialGroup()
                                            .addComponent(txtDataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(lblSexo, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(cmbSexo, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(txtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))))))
            .addGroup(abaPerfilPrestadorLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        abaPerfilPrestadorLayout.setVerticalGroup(
            abaPerfilPrestadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(abaPerfilPrestadorLayout.createSequentialGroup()
                .addGroup(abaPerfilPrestadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblFotoPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(abaPerfilPrestadorLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(abaPerfilPrestadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNome))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(abaPerfilPrestadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDataNascimento)
                            .addComponent(lblSexo)
                            .addComponent(cmbSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(abaPerfilPrestadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblEstado)
                            .addComponent(txtCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCidade))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(abaPerfilPrestadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(abaPerfilPrestadorLayout.createSequentialGroup()
                        .addGroup(abaPerfilPrestadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTelefone)
                            .addComponent(txtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(abaPerfilPrestadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(abaPerfilPrestadorLayout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(abaPerfilPrestadorLayout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addGroup(abaPerfilPrestadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblDataIni1)
                                    .addComponent(txtDataIni1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblDataFim1)
                                    .addComponent(txtDataFim1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 17, Short.MAX_VALUE))
                    .addGroup(abaPerfilPrestadorLayout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addGroup(abaPerfilPrestadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblValor)
                            .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(abaPerfilPrestadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnContratar)
                            .addComponent(btnCancelar))
                        .addGap(52, 52, 52))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(abaPerfilPrestador, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(abaPerfilPrestador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                TelaCriaContrato dialog = new TelaCriaContrato(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel abaPerfilPrestador;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnContratar;
    private javax.swing.JComboBox<String> cmbSexo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCidade;
    private javax.swing.JLabel lblDataFim1;
    private javax.swing.JLabel lblDataIni1;
    private javax.swing.JLabel lblDataNascimento;
    private javax.swing.JLabel lblEstado;
    private javax.swing.JLabel lblFotoPerfil;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblSexo;
    private javax.swing.JLabel lblTelefone;
    private javax.swing.JLabel lblValor;
    private javax.swing.JTextArea txtBio;
    private javax.swing.JTextField txtCidade;
    private javax.swing.JTextField txtDataFim1;
    private javax.swing.JTextField txtDataIni1;
    private javax.swing.JTextField txtDataNascimento;
    private javax.swing.JTextField txtEstado;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtTelefone;
    private javax.swing.JTextField txtValor;
    // End of variables declaration//GEN-END:variables

     private void configTela(){
        setLocationRelativeTo(null); // centraliza tela
        configCampos();
    }
    
    private void configCampos(){
        configCamposData();
    }
    
    private void eventos(){
       clickBtnContratar();
       clickBtnFechar();
    }
    
    public void carregaTela(){
        SimpleDateFormat df = new SimpleDateFormat("dd/MM/yyyy");
        Prestador p = screenMain.pcSelected;
        
        txtNome.setText(p.getNome());
        txtDataNascimento.setText(df.format(p.getDataNascimento()));
        cmbSexo.removeAllItems();
        if(p.getSexo() == 0){
            cmbSexo.addItem("Feminino");
        }else{
            cmbSexo.addItem("Masculino");
        }
        cmbSexo.getItemAt(0);
        txtEstado.setText(p.getEstado());
        txtCidade.setText(p.getCidade());
        txtTelefone.setText(p.getTelefone());
        txtBio.setText(p.getBio());
        
        txtNome.setEditable(false);
        txtDataNascimento.setEditable(false);
        cmbSexo.setEnabled(false);
        txtEstado.setEditable(false);
        txtCidade.setEditable(false);
        txtTelefone.setEditable(false);
        txtBio.setEditable(false);
    }
    
    public void clickBtnContratar(){
        btnContratar.addActionListener(new ActionListener(){
            @Override
            public void actionPerformed(ActionEvent e) {
                
                SimpleDateFormat formatter = new SimpleDateFormat("dd/MM/yyyy");

                Date dataIni;
                Date dataFim;
                try {
                    dataIni = formatter.parse(txtDataIni1.getText());
                    dataFim = formatter.parse(txtDataFim1.getText());
                } 
                catch (ParseException ex) {
                    throw new RuntimeException(ex);
                }

                PreContrato pc = new PreContrato();
                pc.setIdCliente(screenMain.usuarioSistema.getId());
                pc.setIdPrestador(screenMain.pcSelected.getId());
                pc.setValor(Double.parseDouble(txtValor.getText()));
                pc.setServico(screenMain.pcSelected.getTipoServico());
                pc.setDataIni(dataIni);
                pc.setDataFim(dataFim);
                pc.setStatus(0);
                if (pc.insert()) {
                    JOptionPane.showMessageDialog(null, "Cadastro realizado com sucesso!");
                    dispose();
//                    TelaPesquisaServicos tps = new TelaPesquisaServicos();
//                    tps.setVisible(true);
                }

            }
        });
    }

    public void clickBtnFechar(){
        btnCancelar.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                dispose();
                TelaPesquisaServicos tps = new TelaPesquisaServicos();
                tps.setVisible(true);
            }
        });
    }    
    
    public void configCamposData() {
        AbstractDocument doc = (AbstractDocument) txtDataNascimento.getDocument();
        doc.setDocumentFilter(new DataFormatFilter());
        doc = (AbstractDocument) txtDataIni1.getDocument();
        doc.setDocumentFilter(new DataFormatFilter());
        doc = (AbstractDocument) txtDataFim1.getDocument();
        doc.setDocumentFilter(new DataFormatFilter());
    }
}
